### ISSUE TITLE
Deployed using docker-compose and it ignored my app (which i build with maven)

### ISSUE THREAD

**Issue by RaedMou** [hapifhir/hapi-fhir-jpaserver-starter#108]
Hi, 

I installed all the requirements and did the build of my app using mvn clean install , then I ran the command of docker compose , but he ignored my version and installed a new fresh version of HAPI.

How can I deploy my app (which I built) using docker-compose ?
And how can I access to this installed version via docker compose ? any path ?

Thanks

**Comment by j-fbriere** [comment]
You could modify the Dockerfile file to:
```
FROM tomcat:9-jre11

RUN mkdir -p /data/hapi/lucenefiles && chmod 775 /data/hapi/lucenefiles
COPY {your_local_host_folder_where_built_hapi-fhir-jpaserver_war_is_located}/*.war /usr/local/tomcat/webapps/

EXPOSE 8080

CMD ["catalina.sh", "run"]
```
Where {your_local_host_folder_where_built_hapi-fhir-jpaserver_war_is_located} must be changed to the appropriate folder path of your built hapi-fhir-jpaserver.war file.

**Comment by seanmcilvenna** [comment]
The `Dockerfile` provided with hapi-fhir-jpaserver-starter does the work of building the WAR file as part of the `docker build`. If you want your own custom WAR file to be built into the docker image you use, you're going to have to create a customized `Dockerfile` that works differently than the one included in the hapi-fhir-jpaserver-starter repo. @j-fbriere's snippet would do the trick for you. But, just to be clear, that would be a completely separate `Dockerfile` than the one in this repo.

**Comment by RaedMou** [comment]
Hi, I must install tomcat or it will installed on its own in /usr/local/tomcat ?

**Comment by RaedMou** [comment]
I had an error : 

Step 3/5 : COPY /home/USER/hapi-fhir-jpaserver-starter/target/hapi-fhir.war /usr/local/tomcat/webapps/
ERROR: Service 'hapi-fhir-jpaserver-start' failed to build: COPY failed: stat /var/lib/docker/tmp/docker-builder365331628/home/USER/hapi-fhir-jpaserver-starter/target/hapi-fhir.war: no such file or directory

**Comment by j-fbriere** [comment]
At first glance, it seems that the file to copy shouldn't be hapi-fhir.war but rather hapi-fhir-jpaserver.war.
Maybe you should post the Dockerfile file and possibly the docker-compose.yml file you are using and also the step you are doing to build the docker.

**Comment by RaedMou** [comment]
Hi, thank you . 

And how to use PostgreSQL instaed of MySQL ? What configuration should I set up ?

**Comment by j-fbriere** [comment]
You have to modify the docker-compose.yml and the hapi.properties files.
 
Also, it may be a good idea to initialise the HAPI db as a second db and let empty the default superuser postgres db created by the postgres image.
That's why I'm using an additionnal initialisation script, initdb.sql, to create the HAPI db.
 
Here is the docker-compose.yml file:
```
version: "3"
services:
  hapi-fhir-jpaserver-start:
    build: .
    container_name: hapi-fhir-jpaserver-start
    restart: on-failure
    ports:
      - "8080:8080"
  hapi-fhir-postgres:
    image: postgres:latest
    container_name: hapi-fhir-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: {some_postgres_password}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - hapi-fhir-postgres:/var/lib/postgresql/data
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
volumes:
  hapi-fhir-postgres:
```
I also added the initdb.sql file to initialise the HAPI db, to be located at the same folder of the docker-compose.yml file:
```
CREATE USER hapi WITH PASSWORD 'hapi';
CREATE DATABASE hapi;
GRANT ALL PRIVILEGES ON DATABASE hapi TO hapi;
```
Finally here are the modified lines of the hapi.properties file: 
```
...
datasource.driver=org.postgresql.Driver
datasource.url=jdbc:postgresql://hapi-fhir-postgres:5432/hapi
datasource.username=hapi
datasource.password=hapi
...
```
Of course you can change the HAPI db name, username and password to what you want, but be aware that you have to change them in both the initdb.sql and the hapi.properties files.
