### ISSUE TITLE
Add postgres drivers to hosted Docker image

### ISSUE THREAD

**Issue by citizenrich** [hapifhir/hapi-fhir-jpaserver-starter#109]
The hosted image at https://hub.docker.com/r/hapiproject/hapi fails if configured at runtime to use postgres in hapi.properties:
```
"Factory method 'dataSource' threw exception; nested exception is java.lang.ClassNotFoundException: org.postgresql.Driver"
```
This suggests that the hosted images are not built with postgres drivers. I wonder if there's a possibility for them to be added.

**Comment by seanmcilvenna** [comment]
If you tell me what the dependency is that I would add to the pom.xml file, I'd be willing to rebuild one or two tags with it...

**Comment by citizenrich** [comment]
It could be a different issue - that hapi.properties is being overridden by some other file. For example, using the mysql instructions from the readme, the dialect in the hapi.properties file (I'm running with mvn jetty), is not picked up. I get:
```
Using dialect: org.hibernate.dialect.H2Dialect
```
When hapi.properties is:
```
hibernate.dialect=org.hibernate.dialect.MySQL5InnoDBDialect
```
So, it could be that the pg config stuff is not being picked-up. If you think that's a separate issue, I can create a new one.

**Comment by seanmcilvenna** [comment]
Yah. Sounds like the custom config isn't being picked up for sure... do you have a docker-compose.yml or `docker run` you could share with me to help determine why?

**Comment by citizenrich** [comment]
Thanks! Sure... I'm seeing the same issue with mysql as well. So, I hope you don't mind if I share a minimum worked example using mysql and I'll revert with postgres later.

This uses docker for mysql and mvn run:jetty directly. Tested with branch v5.0.0. 

Edit hapi.properties to:
```
datasource.driver=com.mysql.jdbc.Driver
datasource.url=jdbc:mysql://127.0.0.1:3306/hapi?useSSL=false
hibernate.dialect=org.hibernate.dialect.MySQL5InnoDBDialect
datasource.username=admin
datasource.password=admin
```

Fire up mysql in a container:
```
version: "3"

services:

  mysql:
    container_name: hapi-mysql
    image: mysql:5.7
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    environment:
      MYSQL_DATABASE: 'hapi'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
      MYSQL_ROOT_PASSWORD: 'admin'
    ports:
      - "3306:3306"
```

```
mvn jetty:run
```

**Comment by seanmcilvenna** [comment]
Do are you running `mvn install` before `mvn run:jetty`? May need to run install after making hapi.properties changes and before run:jetty.

**Comment by citizenrich** [comment]
Ahh, nice catch. No, I had not been. I've tried it but doing `mvn install -DskipTests` or `mvn clean install -DskipTests` doesn't result in changes being picked up in hapi.properties. I still see `Using dialect: org.hibernate.dialect.H2Dialect`

**Comment by seanmcilvenna** [comment]
So, just to confirm...
You've cloned the repository, made changes to the hapi.properties file in the `src/main/resources` directory, and then ran `mvn install` followed by `mvn run:jetty`?

**Comment by citizenrich** [comment]
Yes. Let me add the particulars in case there's a version issue and do this freshly. Also, there's another issue.

```
$ java --version
openjdk 13.0.2 2020-01-14
OpenJDK Runtime Environment (build 13.0.2+8)
OpenJDK 64-Bit Server VM (build 13.0.2+8, mixed mode, sharing)
$ mvn --version
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /usr/local/Cellar/maven/3.6.3_1/libexec
Java version: 13.0.2, vendor: N/A, runtime: /usr/local/Cellar/openjdk/13.0.2+8_2/libexec/openjdk.jdk/Contents/Home
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.15.5", arch: "x86_64", family: "mac"
```

Fresh clone:
```
$ git clone git@github.com:hapifhir/hapi-fhir-jpaserver-starter.git
Cloning into 'hapi-fhir-jpaserver-starter'...
remote: Enumerating objects: 99, done.
remote: Counting objects: 100% (99/99), done.
remote: Compressing objects: 100% (41/41), done.
remote: Total 1561 (delta 23), reused 81 (delta 13), pack-reused 1462
Receiving objects: 100% (1561/1561), 455.62 KiB | 3.02 MiB/s, done.
Resolving deltas: 100% (532/532), done.
$ cd hapi-fhir-jpaserver-starter
```

Edit the file src/main/resources/hapi.properties as follows:
```
# mysql
datasource.driver=com.mysql.jdbc.Driver
datasource.url=jdbc:mysql://127.0.0.1:3306/hapi?useSSL=false
hibernate.dialect=org.hibernate.dialect.MySQL5InnoDBDialect
datasource.username=admin
datasource.password=admin
# datasource.driver=org.h2.Driver
# datasource.url=jdbc:h2:file:./target/database/h2
# datasource.username=
# datasource.password=
server.name=Local Tester
server.id=home
test.port=
```

Fire up docker-compose in another terminal to run this:
```
version: "3"

services:

  mysql:
    container_name: hapi-mysql
    image: mysql:5.7
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    environment:
      MYSQL_DATABASE: 'hapi'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
      MYSQL_ROOT_PASSWORD: 'admin'
    ports:
      - "3306:3306"
```

Then:
```
mvn clean install -DskipTests
...
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  20.239 s
[INFO] Finished at: 2020-06-30T11:26:38-04:00
[INFO] ------------------------------------------------------------------------
```


```
$ mvn run:jetty
[ERROR] No plugin found for prefix 'run' in the current project and in the plugin groups [org.apache.maven.plugins, org.codehaus.mojo] available from the repositories [local (/Users/richard/.m2/repository), central (https://repo.maven.apache.org/maven2)] -> [Help 1]
```
I clean out the cache for maven at $HOME/.m2/ as a precaution and then redo the maven command, and now am in a loop where it can't find run.

**Comment by seanmcilvenna** [comment]
I think it's supposed to be `mvn jetty:run`.
Sorry, I think I may have led you wrong a couple messages ago. I don't use `mvn jetty:run` so I'm not the most familiar with that approach.

**Comment by citizenrich** [comment]
My mistake, I should have seen that! 

In any case, following the above code I shared, I get "org.hibernate.dialect.H2Dialect".

**Comment by seanmcilvenna** [comment]
hmmm... it seems like you're doing everything correct. again, not having any experience with `mvn jetty:run`, I would venture to guess that it has something to do with how maven runs the application. have you considered running hapi using docker? I have several installations of hapi via docker, and it works fine. with that said, I'm running 4.2 of hapi-fhir-jpaserver-starter in docker, and haven't gotten to upgrade to 5.0, yet. so, maybe it is an issue with the latest version of the code...

**Comment by seanmcilvenna** [comment]
Yah, the issue that just came in (#113) makes me think this is more of an issue with using `mvn jetty:run`

**Comment by citizenrich** [comment]
That would make a lot of sense. Should I then try to pass dialect and other params on the command line to Jetty?

**Comment by seanmcilvenna** [comment]
That seems like a solution, to me... Not sure if this works, but maybe you can do something like `mvn jetty:run -Dhibernate.dialect=XXXXX`

**Comment by citizenrich** [comment]
Thanks! The support is very much appreciated and sorry for taking so much of your time. My use case has been to try to debug issues that an implementation is having with using hapi with postgres, either with docker or without. I used the `mvn jetty:run` approach to iterate fast on the hapi.properties to ensure that the config is correct. But that approach isn't working if `mvn jetty:run` doesn't see all of that file. 

So, I can build war files. It's not clear to me, though, if the war files are built, either in a container or directly, will changes to hapi.properties be picked up or does the war file need to be rebuilt? If rebuilt, it would seem sort of counter-intuitive because docker containers are meant for making changes, ie to databases, at runtime, not build time.

**Comment by seanmcilvenna** [comment]
_That_ is an approach I can say that I've used... :)
To build the war file, just run `mvn install`. Any changes to the hapi.properties file in the `src/main/resources` directory should be included in the WAR file at that time. The WAR file will be placed in the `target` directory after `mvn install` completes. Even _after_ the WAR file is built, you can open the WAR file up with a compression tool like 7zip and make modifications to the hapi.properties file embedded in the WAR file/archive.
One other note: You can _tell_ HAPI where the custom config is by setting a java property, either with `-Dhapi.properties=PATH/TO/FILE` or similarly via an environment variable `JAVA_OPTS=-Dhapi.properties=PATH/TO/FILE`.

**Comment by citizenrich** [comment]
Thanks, I'll start trying war files. 

This is a 'docker-compose plus hapi.properties' way to reproduce the hapi.properties not picking up the db, in this case postgres. I'm just putting this here for others coming later if they see how to make it work. If someone else figures it out, please do share.

In an empty folder, create a docker-compose and a hapi.properties.

docker-compose:
```
version: "3"
services:
  hapi-fhir-jpaserver-start:
    image: hapiproject/hapi:v4.2.0
    container_name: hapi-fhir-jpaserver-start
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS='-Dhapi.properties=/usr/local/tomcat/conf/hapi.properties'
    volumes:
      - ./hapi.properties:/usr/local/tomcat/conf/hapi.properties
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: hapi
    # not needed for networking between containers but for troubleshooting
    ports:
      - "5432:5432"
```

copy a new hapi.properties and change only these lines:
```
# add postgres
datasource.driver=org.postgresql.Driver
datasource.url=jdbc:postgresql://db:5432/hapi
hibernate.dialect=org.hibernate.dialect.PostgreSQL95Dialect
datasource.username=admin
datasource.password=admin
# comment out derby
# datasource.driver=org.h2.Driver
# datasource.url=jdbc:h2:file:./target/database/h2
# datasource.username=
# datasource.password=
```

Run `docker-compose up`. There should be a line saying what Java options were found:
```
[main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dhapi.properties=/usr/local/tomcat/conf/hapi.properties
```

That is correct, as we're mounting in the local hapi.properties file. But, the hibernate dialect will not be correct:
```
[main] INFO  org.hibernate.dialect.Dialect [Dialect.java:172] HHH000400: Using dialect: org.hibernate.dialect.H2Dialec
```
