### ISSUE TITLE
binary_storage_enabled doesn't work

### ISSUE THREAD

**Issue by patrick-werner** [hapifhir/hapi-fhir-jpaserver-starter#179]
When enabling: `binary_storage_enabled`and persisting binaries above the threshold i get the following results:

- POSTing works, a Binary ID is returned
- GET with a non FHIR accept value (e.g. application/fhir#json) returns:
````json
{
    "resourceType": "Binary",
    "id": "5152",
    "meta": {
        "versionId": "1",
        "lastUpdated": "2020-11-30T12:10:32.690+01:00",
        "source": "#mcsSHNdq1duFICWf"
    },
    "contentType": "application/pdf",
    "_data": {
        "extension": [
            {
                "url": "http://hapifhir.io/fhir/StructureDefinition/externalized-binary-id",
                "valueString": "ODNXdGALkf6fWYwPL02OqtmpstSkMK8FAhsahvwAJTnlmqMkI3ShvS4pXzYs6tJgLHcWXLaT69ZEk43ApzcRXZwoDQFMlgojX1li"
            }
        ]
    }
}
````
When setting accept to application/pdf the response body is empty.

**Comment by tadgh** [comment]
Hey @patrick-werner , This is what i would expect to see here. To actually stream the binary data down to your machine, you would need to use the `$binary-access-read` operation. e.g. `[base]/Binary/5152/$binary-access-read` with the appropriate content type. Or am I missing some nuance?

**Comment by patrick-werner** [comment]
Hi @tadgh,

the FHIR Spec states: "When the read request has some other type in the Accept header, then the content should be returned with the content type stated in the resource in the Content-Type header. E.g. if the content type in the resource is "application/pdf", then the content should be returned as a PDF directly. The _summary parameter does not apply in this case." https://www.hl7.org/fhir/binary.html#rest

So when doing a READ with application/pdf in the accepted header, the FHIR Server should return the raw PDF directly. Hapi returns an empty return body if setting the accept header to the original mime/type of the resource.

**Comment by tadgh** [comment]
Ahh I was indeed missing the nuance. Thanks much Patrick, will look at getting this implemented, i think it is a missing feature in core hapi-fhir.

**Comment by patrick-werner** [comment]
reopening as this is still not working im 7.2.0
fyi @tadgh

**Comment by lvbartow** [comment]
Hello, I came across this bug yesterday and I've been letting some hair on my desk as I can't get content-negotiation working. You would suggest it is a server issue ?
As you, I can successfully upload a Binary containing a PDF but I am not able to download it, even with good Content-Type on resource and properly set Accept header; the JSON Binary's description is always given instead.
If you have any tips to get round of the problem before it is fixed...
Thanks

**Comment by tadgh** [comment]
Did you attempt the $binary-access-read operation as I outlined above? 
e.g.
```
GET /Binary/[id]/$binary-access-read?path=Binary.data
```
^-- the above will stream the binary data in the content-type that is defined in the binary


@patrick-werner Yeah this was totally forgotten about. My apologies. Is there any chance you could write up a failing unit test for HAPI-FHIR? It is _much_ easier to get OSS requests done if we can start with a failing test. I would recommend a test in [this class](https://github.com/hapifhir/hapi-fhir/blob/94c25d37a04cb3663d72ee334ef12e1a0b3009ac/hapi-fhir-jpaserver-test-r4/src/test/java/ca/uhn/fhir/jpa/provider/r4/BinaryAccessProviderR4Test.java#L64-L64).

**Comment by lvbartow** [comment]
Yes, even with the operation I'm not able to make it work; here are some Postman screenshots :   

![image](https://github.com/hapifhir/hapi-fhir-jpaserver-starter/assets/114496815/ef6ec5cf-4a5c-424d-8a23-2c0cd4429a9e)

![image](https://github.com/hapifhir/hapi-fhir-jpaserver-starter/assets/114496815/e7c92ff5-e7c7-4330-b841-786acbb5abd0)

**Comment by tadgh** [comment]
I assume you are using the JPAServerStarter. Have you enabled the `binary_storage_enabled` property? The code requires it to load that ResourceProvider. See: https://github.com/hapifhir/hapi-fhir-jpaserver-starter/blob/8ef50832d3459d4eb35ecb4f116c580475acb59d/src/main/java/ca/uhn/fhir/jpa/starter/common/StarterJpaConfig.java#L353-L353

**Comment by lvbartow** [comment]
Yes it is set. Here is my application.yaml :
```
spring:
  datasource:
    url: 'jdbc:postgresql://db:5432/hapi'
    username: admin
    password: admin
    driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate.dialect: ca.uhn.fhir.jpa.model.dialect.HapiFhirPostgres94Dialect
      hibernate.search.enabled: false
hapi:
  fhir:
    ### This flag when enabled to true, will avail evaluate measure operations from CR Module.
    ### Flag is false by default, can be passed as command line argument to override.
    cr:
      enabled: false

    cdshooks:
      enabled: true
      clientIdHeaderName: client_id

    ### This enables the swagger-ui at /fhir/swagger-ui/index.html as well as the /fhir/api-docs (see https://hapifhir.io/hapi-fhir/docs/server_plain/openapi.html)
    openapi_enabled: true
    ### This is the FHIR version. Choose between, DSTU2, DSTU3, R4 or R5
    fhir_version: R4
    ### Flag is false by default. This flag enables runtime installation of IG's.
    ig_runtime_upload_enabled: false
    ### This flag when enabled to true, will avail evaluate measure operations from CR Module.

    narrative_enabled: false
    mdm_enabled: false
    mdm_rules_json_location: "mdm-rules.json"
    #    local_base_urls:
    #      - https://hapi.fhir.org/baseR4
    logical_urls:
      - http://terminology.hl7.org/*
      - https://terminology.hl7.org/*
      - http://snomed.info/*
      - https://snomed.info/*
      - http://unitsofmeasure.org/*
      - https://unitsofmeasure.org/*
      - http://loinc.org/*
      - https://loinc.org/*
    #    partitioning:
    #      allow_references_across_partitions: false
    #      partitioning_include_in_search_hashes: false
    cors:
      allow_Credentials: true
      # These are allowed_origin patterns, see: https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/cors/CorsConfiguration.html#setAllowedOriginPatterns-java.util.List-
      allowed_origin:
        - '*'

    # Search coordinator thread pool sizes
    search-coord-core-pool-size: 20
    search-coord-max-pool-size: 100
    search-coord-queue-capacity: 200

    home:
      name: Local Tester
      server_address: 'http://localhost:8080/fhir'
      refuse_to_fetch_third_party_urls: false
      fhir_version: R4
      
    validation:
      requests_enabled: true
      responses_enabled: true
      binary_storage_enabled: true
    inline_resource_storage_below_size: 4000


```
