### ISSUE TITLE
Configuration option to use the ApacheProxyAddressStrategy

### ISSUE THREAD

**Issue by chgl** [hapifhir/hapi-fhir-jpaserver-starter#207]
I've had some issues with some proxy server configuration which were resolved by using the `ApacheProxyAddressStrategy`. The implementation is over at:

https://github.com/chgl/hapi-fhir-jpaserver-starter/tree/configure-apache-proxy-strategy

It adds two new configuration options:

```yaml
hapi:
  fhir:
    ### enable to use the ApacheProxyAddressStrategy which uses X-Forwarded-* headers
    ### to determine the FHIR server address
    use_apache_address_strategy: false
    ### forces the use of the https:// protocol for the returned server address.
    ### alternatively, it may be set using the X-Forwarded-Proto header.
    use_apache_address_strategy_https: false
```

If you think it makes sense to include these options in the official jpaserver-starter, I'd be happy to create a PR!
