### ISSUE TITLE
How can I change hapi server version?

### ISSUE THREAD

**Issue by LiShangAn** [hapifhir/hapi-fhir-jpaserver-starter#235]
Hi, 

This is my docker-compose yaml file, I would like to set the version of hapi fhir server to R5. But when I set the environment variable >  hapi.fhir.fhir_version: R5, the below error happens.

![image](https://user-images.githubusercontent.com/16515572/118257597-65977c80-b4e1-11eb-8c05-d14f2288bcef.png)

```
version: '3'
services:
  hapi:
    container_name: hapi
    image: hapiproject/hapi:latest
    ports:
      - 8090:8080
    restart: always
    configs:
      - source: hapi
      - target: /data/hapi/application.yaml
    environment:
      hapi.fhir.fhir_version: R5
configs:
  hapi:
     external: true
```
