### ISSUE TITLE
[FR] Allow to disable the connection pooler

### ISSUE THREAD

**Issue by ZuSe** [hapifhir/hapi-fhir-jpaserver-starter#239]
Some weeks ago the hikari connection pooler has been introduced. 
However it seems to bite with existing poolers so it would be good to have an option to disable it.

We are using pgpool-II in front of our postgres cluster (v13.3)

See attached log for more information. 
[logfhir.log](https://github.com/hapifhir/hapi-fhir-jpaserver-starter/files/6522964/logfhir.log)

**Comment by jkiddo** [comment]
Related: https://github.com/brettwooldridge/HikariCP/issues/1042

**Comment by jkiddo** [comment]
Would you check if it is sufficient for you to simply configure it as follows:

````
jpa:
    max-active: 15
    type: org.springframework.jdbc.datasource.SimpleDriverDataSource
    # database connection pool size
    #hikari:
      #maximum-pool-size: 10
````

**Comment by ZuSe** [comment]
Hi @jkiddo  seems to work. Thanks!

**Comment by bauerjs1** [comment]
I had the same issue, but the above suggestion did not work for me. After digging a little bit, I found that the configuration keys in the application.yaml are different (it's `datasource` instead of `jpa`), maybe they have changed since then.

Since I deploy HAPI via Helm chart, I tried to achieve this by ENVs and the following seems to work:
```yaml
extraEnv:
  - name: SPRING_DATASOURCE_HIKARI
    value: "null"
  - name: SPRING_DATASOURCE_MAX_ACTIVE
    value: "15"
  - name: SPRING_DATASOURCE_TYPE
    value: org.springframework.jdbc.datasource.SimpleDriverDataSource
```
