### ISSUE TITLE
Hapi Fhir inside docker doesn't seem to work (Weird behavior)

### ISSUE THREAD

**Issue by longnguyen2306** [hapifhir/hapi-fhir-jpaserver-starter#34]
Hello, 
your repo works very well with mvn jetty:run, however the docker version is pretty weird. 

1) The start page is http://localhost:8080 instead of http://localhost:8080/hapi-fhir-jpaserver.

2) I only get 404 (Screen shot):

![Screenshot from 2019-06-14 03-35-16](https://user-images.githubusercontent.com/37987580/59477561-fc6ee080-8e55-11e9-93df-fe4690d8e6b7.png)

Following is my docker-compose:

```yaml
version: "2"
services:
  happy:
    build: .
    image: fhir
    container_name: fhir
    restart: always
    ports:
      - 8080:8080
```
