### ISSUE TITLE
Custom Configuration not working

### ISSUE THREAD

**Issue by inowshin19** [hapifhir/hapi-fhir-jpaserver-starter#381]
I tried custom configuration in HAPI FHIR. I modified the code in the application.yaml file to enable email subscription and then set the SPRING_CONFIG_LOCATION=file:<the path of the directory of modified application.yaml file> in docker-compose.yml. 

I tried to follow this link: https://github.com/hapifhir/hapi-fhir-jpaserver-starter/wiki/Configuration

The server does not start. Can you please tell me what I am doing wrong?

**Comment by lanesky** [comment]
What is the error you are encountering?
I tried the docke-compose file below, it seems to work fine and the custom configuration works as expected.

```
version: "3"
services:
  hapi-fhir-jpaserver-start:
    build: .
    container_name: hapi-fhir-jpaserver-start
    restart: on-failure
    ports:
      - "8080:8080"
    volumes:
      - ${PWD}/data/hapi:/data/hapi
    environment:
      SPRING_CONFIG_LOCATION: 'file:///data/hapi/application.yaml'
  hapi-fhir-mysql:
    image: mysql:latest
    container_name: hapi-fhir-mysql
    #https://dev.mysql.com/doc/refman/8.0/en/identifier-case-sensitivity.html
    command: --lower_case_table_names=1
    restart: always
    environment:
      MYSQL_DATABASE: 'hapi'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
      MYSQL_ROOT_PASSWORD: 'admin'
    volumes:
      - hapi-fhir-mysql:/var/lib/mysql
volumes:
  hapi-fhir-mysql:
```
