### ISSUE TITLE
Bundle.entry missing in search results with Lucene index enabled

### ISSUE THREAD

**Issue by sidharthramesh** [hapifhir/hapi-fhir-jpaserver-starter#383]
I want to enable text search on certain token fields (identifier / phone) using the HAPI JPA FHIR server. As per the documentation here: https://hapifhir.io/hapi-fhir/docs/server_jpa/elastic.html, I've enabled certain environment variables as below. 

Note: I am not using Elasticsearch.
 
## Steps to reproduce:
Use docker image: `hapiproject/hapi:v6.0.1` with database (db) `postgres:14`. I'm using this `docker-compose.yaml` file with these environment variables:
```yaml
version: "3"
services:
  fhir:
    image: hapiproject/hapi:v6.0.1
    environment:
      - spring.datasource.url=jdbc:postgresql://db:5432/fhir
      - spring.datasource.username=fhir
      - spring.datasource.password=fhir
      - spring.datasource.driverClassName=org.postgresql.Driver
      - spring.jpa.properties.hibernate.dialect=ca.uhn.fhir.jpa.model.dialect.HapiFhirPostgres94Dialect
      - hapi.advanced_lucene_indexing=true
      - hapi.fhir.store_resource_in_lucene_index_enabled=true
      - mdm_enabled=true
    ports:
      - 8080:8080
  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=fhir
      - POSTGRES_PASSWORD=fhir
      - POSTGRES_DB=fhir
```

POST a Patient resource:
```json
 {
	"resourceType": "Patient",
	"identifier": [
		{
			"system": "hospital_id",
			"value": "1256744"
		}	

	],
	"name": [
		{
			"text": "Sidharth Ramesh"
		}
	],
	"gender": "male"
}
```
Requesting all patients in the server using `GET /Patient` returns
```json
{
	"resourceType": "Bundle",
	"id": "63ec851c-e0f8-4e30-be58-382baf3e0f2a",
	"meta": {
		"lastUpdated": "2022-06-03T10:58:34.260+00:00"
	},
	"type": "searchset",
	"total": 1,
	"link": [
		{
			"relation": "self",
			"url": "https://example.com/fhir/Patient/"
		}
	]
}
```

Note that the total number of resources is returned correctly, however, the `entry` field is empty.
This only happens when `hapi.fhir.store_resource_in_lucene_index_enabled` is set to `true`.

Upon investigating further, search using an identifier using the query: `Patient?identifier=1256744` returns the correct `total`, still without the `entry` field.:
```json
{
	"resourceType": "Bundle",
	"id": "b256cb88-29e5-4fbf-bd99-d4bc4c074e30",
	"meta": {
		"lastUpdated": "2022-06-03T11:06:38.562+00:00"
	},
	"type": "searchset",
	"total": 1,
	"link": [
		{
			"relation": "self",
			"url": "https://example.com/fhir/Patient?identifier=1256744"
		}
	]
}
```

However, searching using text modifier on identifier with BOTH partial subset of the string `Patient?identifier:text=1256` or the complete identifier `Patient?identifier:text=1256744` incorrectly returns zero total results:
```json
{
	"resourceType": "Bundle",
	"id": "29adf7a9-52de-4bbe-8531-daa58c4029a1",
	"meta": {
		"lastUpdated": "2022-06-03T11:07:38.415+00:00"
	},
	"type": "searchset",
	"total": 0,
	"link": [
		{
			"relation": "self",
			"url": "https://example.com/fhir/Patient?identifier%3Atext=1256744"
		}
	]
}
```

There are no errors on the server logs.

## Expected results
1. All the entries are returned in the search response Bundle
2. Partial and complete string matchs are returned as results for searches on tokens using the `:text` modifier
