### ISSUE TITLE
jpaserver docker-image with postresql

### ISSUE THREAD

**Issue by kellerjo** [hapifhir/hapi-fhir-jpaserver-starter#388]
Hello,
I am trying to set up the server as a docker image together with a postresql database. When starting the compose file, I get the following error:
org.postgresql.util.PSQLException: ERROR: relation "hfj_search" does not exist

Is there a schema file I am missing?

**Comment by KevinDougan-SmileCDR** [comment]
Are you pointing to a pre-existing database with a schema that has already been initialized?

Does it work if you point to an empty schema and let it initialize the database during startup?

**Comment by kellerjo** [comment]
Thanks for the answer!
I used a fresh porstgre docker instance with no existing database. I have for now reverted to using the h2 database

**Comment by alxcost** [comment]
Hi. This issue still occurs on PostgreSQL databases with the most recent versison.
This is with fresh porstgres instances with no existing database or schemas.

**Comment by afifurrohman-id** [comment]
This issue still occur on postgres 17.x

**Comment by vascokk** [comment]
> This issue still occur on postgres 17.x

I had this issue due to docker-compose  misonfiguration. Here is the correct one:

docker-compose.yaml:

```
version: "3"
services:
  hapi-fhir-jpaserver-start:
    build: .
    container_name: hapi-fhir-jpaserver-start
    restart: on-failure
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/hapi"
      SPRING_DATASOURCE_USERNAME: "admin"
      SPRING_DATASOURCE_PASSWORD: "admin"
      SPRING_DATASOURCE_DRIVERCLASSNAME: "org.postgresql.Driver"
    ports:
      - "8080:8080"
    configs:
      - source: hapi
        target: /app/config/application.yaml
  db:
    image: postgres:15-alpine
    container_name: hapi-fhir-postgres
    restart: always
    environment:
      POSTGRES_DB: "hapi"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    volumes:
      - hapi-fhir-postgres:/var/lib/postgresql/data
volumes:
  hapi-fhir-postgres:
configs:
  hapi:
     file: ./hapi.application.yaml
```

./hapi.application.yaml

```
spring:
  datasource:
    url: 'jdbc:postgresql://db:5432/hapi'
    username: admin
    password: admin
    driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate.dialect: ca.uhn.fhir.jpa.model.dialect.HapiFhirPostgresDialect
      hibernate.search.enabled: false
```
