### ISSUE TITLE
Unknown job definition ID: REINDEX when trying to create search parameters

### ISSUE THREAD

**Issue by ktadiko** [hapifhir/hapi-fhir-jpaserver-starter#461]
Server fails with error below when trying to create some search parameters as part of start up. 

```
server-fhirserver-1  | Caused by: java.lang.IllegalArgumentException: HAPI-2063: Unknown job definition ID: REINDEX
server-fhirserver-1  |  at ca.uhn.fhir.batch2.coordinator.JobCoordinatorImpl.lambda$startInstance$0(JobCoordinatorImpl.java:93)
server-fhirserver-1  |  at java.base/java.util.Optional.orElseThrow(Unknown Source)
server-fhirserver-1  |  at ca.uhn.fhir.batch2.coordinator.JobCoordinatorImpl.startInstance(JobCoordinatorImpl.java:93)
server-fhirserver-1  |  at ca.uhn.fhir.jpa.dao.BaseHapiFhirResourceDao.requestReindexForRelatedResources(BaseHapiFhirResourceDao.java:981)
server-fhirserver-1  |  at ca.uhn.fhir.jpa.dao.r4.FhirResourceDaoSearchParameterR4.reindexAffectedResources(FhirResourceDaoSearchParameterR4.java:59)
server-fhirserver-1  |  at ca.uhn.fhir.jpa.dao.r4.FhirResourceDaoSearchParameterR4.postPersist(FhirResourceDaoSearchParameterR4.java:66)
server-fhirserver-1  |  at ca.uhn.fhir.jpa.dao.r4.FhirResourceDaoSearchParameterR4.postPersist(FhirResourceDaoSearchParameterR4.java:49)
server-fhirserver-1  |  at ca.uhn.fhir.jpa.dao.BaseHapiFhirDao.updateEntity(BaseHapiFhirDao.java:1399)
server-fhirserver-1  |  at ca.uhn.fhir.jpa.dao.BaseHapiFhirResourceDao.doCreateForPostOrPut(BaseHapiFhirResourceDao.java:350)
server-fhirserver-1  |  at ca.uhn.fhir.jpa.dao.BaseHapiFhirResourceDao.doUpdate(BaseHapiFhirResourceDao.java:1752)
server-fhirserver-1  |  at ca.uhn.fhir.jpa.dao.BaseHapiFhirResourceDao.lambda$update$18(BaseHapiFhirResourceDao.java:1688)
server-fhirserver-1  |  at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140)
server-fhirserver-1  |  at ca.uhn.fhir.jpa.dao.tx.HapiTransactionService.doExecuteCallback(HapiTransactionService.java:150)
server-fhirserver-1  |  at ca.uhn.fhir.jpa.dao.tx.HapiTransactionService.execute(HapiTransactionService.java:84)
server-fhirserver-1  |  at ca.uhn.fhir.jpa.dao.BaseHapiFhirResourceDao.update(BaseHapiFhirResourceDao.java:1688)
server-fhirserver-1  |  at ca.uhn.fhir.jpa.dao.BaseHapiFhirResourceDao.update(BaseHapiFhirResourceDao.java:1661)
server-fhirserver-1  |  at ca.uhn.fhir.jpa.dao.BaseHapiFhirResourceDao.update(BaseHapiFhirResourceDao.java:1656)
server-fhirserver-1  |  at ca.uhn.fhir.jpa.dao.BaseHapiFhirResourceDao.update(BaseHapiFhirResourceDao.java:1638)
server-fhirserver-1  |  at ca.uhn.fhir.jpa.dao.BaseHapiFhirResourceDao$$FastClassBySpringCGLIB$$5578fb67.invoke(<generated>)
server-fhirserver-1  |  at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
server-fhirserver-1  |  at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793)
server-fhirserver-1  |  at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
server-fhirserver-1  |  at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
server-fhirserver-1  |  at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:137)
server-fhirserver-1  |  ... 90 common frames omitted
```

### application.yaml changes
```yml
jpa:
    properties:
      hibernate.dialect: ca.uhn.fhir.jpa.model.dialect.HapiFhirPostgres94Dialect
      hibernate.search.enabled: true
      hibernate.search.backend.type: elasticsearch
      hibernate.search.backend.analysis.configurer: ca.uhn.fhir.jpa.search.elastic.HapiElasticsearchAnalysisConfigurer

elasticsearch:
  debug:
    pretty_print_json_log: false
    refresh_after_write: false
  enabled: true
  password: admin
  required_index_status: YELLOW
  rest_url: 'opensearch:9200'
  protocol: 'http'
  schema_management_strategy: CREATE
  username: admin
```

### docker-compose.yaml
```yml
version: "3.9"
services:
    fhirserver:
        build:
            context: "."
            dockerfile: ./Dockerfile
        command: sh -c "/wait-for-it.sh postgres-fhir:5432 &&
            java -Dspring-boot.run.jvmArguments=\"-Xms2G -Xmx6G\" -jar /fhirserver/main.war"
        ports:
            - "8008:8008"
        volumes:
            - ./wait-for-it.sh:/wait-for-it.sh
        depends_on:
            postgres-fhir:
                condition: service_started
            opensearch:
                condition: service_healthy
    postgres-fhir:
        image: postgres:12-alpine
        ports:
            - "5454:5432"
        volumes:
            - ./data/postgres_fhir:/var/lib/postgresql/data
        environment:
            - POSTGRES_HOST=postgres-fhir
            - POSTGRES_USER=user
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=fhir_db
    opensearch:
        image: opensearchproject/opensearch:1.2.0
        expose:
            - 9200
        environment:
            - discovery.type=single-node
            - bootstrap.memory_lock=true
            - compatibility.override_main_response_version=true
            - "DISABLE_SECURITY_PLUGIN=true"
            - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
            memlock:
                soft: -1 # Set memlock to unlimited (no soft or hard limit)
                hard: -1
            nofile:
                soft: 65536 # Maximum number of open files for the opensearch user - set to at least 65536
                hard: 65536
        volumes:
          - ./data/opensearch:/usr/share/opensearch/data
        healthcheck:
          test: curl -s curl http://localhost:9200 -ku 'admin:admin' >/dev/null || exit 1
          interval: 30s
          timeout: 10s
          retries: 5
```
