### ISSUE TITLE
Static content redirect - error (too many redirects) when the path has trailing slash

### ISSUE THREAD

**Issue by costateixeira** [hapifhir/hapi-fhir-jpaserver-starter#485]
when using the static content hosting feature, 
```yaml
hapi:
  fhir:
    staticLocation: file:/apps
```
provides the correct behaviour. 
However, when there is a trailing slash, e.g.
```yaml
hapi:
  fhir:
    staticLocation: file:/apps/
```

The redirect doesn't work - 
`http://localhost:8080/static/index.html` - ends up at 
`http://localhost:8080/static//index.html and the browser gives up after too many redirects
