### ISSUE TITLE
docker-compose: Unable to start index. Unable to initialize index directory: /app/target

### ISSUE THREAD

**Issue by juvarabrera** [hapifhir/hapi-fhir-jpaserver-starter#493]
# What I did before the error:
1. `git clone ...` then `cd`
2. Change `ports` in `docker-compose.yml`
3. Change `url`, `username`, `password`, `driverClassName` in `spring.datasource` in `src/main/resources/application.yaml`
4. Change `hibernate.dialect` in `spring.jpa.properties` in `src/main/resources/application.yaml`
5. Run `docker-compose up --build`

# Error Log

After running `docker-compose up --build`, I'm getting this error in `hapi-fhir-jpaserver-start` container

```
hapi-fhir-jpaserver-start    | Caused by: org.hibernate.search.util.common.SearchException: HSEARCH000520: Hibernate Search encountered failures during bootstrap. Failures:
hapi-fhir-jpaserver-start    | 
hapi-fhir-jpaserver-start    |     index 'TermConcept': 
hapi-fhir-jpaserver-start    |         failures: 
hapi-fhir-jpaserver-start    |           - HSEARCH600154: Unable to start index: HSEARCH600015: Unable to initialize index directory: /app/target
hapi-fhir-jpaserver-start    |             Context: index 'TermConcept'
hapi-fhir-jpaserver-start    |     index 'ResourceTable': 
hapi-fhir-jpaserver-start    |         failures: 
hapi-fhir-jpaserver-start    |           - HSEARCH600154: Unable to start index: HSEARCH600015: Unable to initialize index directory: /app/target
hapi-fhir-jpaserver-start    |             Context: index 'ResourceTable'
hapi-fhir-jpaserver-start    | 	at org.hibernate.search.engine.reporting.spi.RootFailureCollector.checkNoFailure(RootFailureCollector.java:53)
hapi-fhir-jpaserver-start    | 	at org.hibernate.search.engine.common.impl.SearchIntegrationPartialBuildStateImpl$SearchIntegrationFinalizerImpl.finalizeIntegration(SearchIntegrationPartialBuildStateImpl.java:188)
hapi-fhir-jpaserver-start    | 	at org.hibernate.search.mapper.orm.bootstrap.impl.HibernateOrmIntegrationPartialBuildState.doBootSecondPhase(HibernateOrmIntegrationPartialBuildState.java:75)
hapi-fhir-jpaserver-start    | 	at org.hibernate.search.mapper.orm.bootstrap.impl.HibernateOrmIntegrationBooterImpl.bootNow(HibernateOrmIntegrationBooterImpl.java:176)
hapi-fhir-jpaserver-start    | 	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
hapi-fhir-jpaserver-start    | 	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
hapi-fhir-jpaserver-start    | 	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
hapi-fhir-jpaserver-start    | 	at org.hibernate.search.mapper.orm.bootstrap.impl.HibernateSearchSessionFactoryObserver.sessionFactoryCreated(HibernateSearchSessionFactoryObserver.java:41)
hapi-fhir-jpaserver-start    | 	at org.hibernate.internal.SessionFactoryObserverChain.sessionFactoryCreated(SessionFactoryObserverChain.java:35)
hapi-fhir-jpaserver-start    | 	at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:402)
hapi-fhir-jpaserver-start    | 	at org.hibernate.boot.internal.SessionFactoryBuilderImpl.build(SessionFactoryBuilderImpl.java:471)
hapi-fhir-jpaserver-start    | 	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:1498)
hapi-fhir-jpaserver-start    | 	at org.hibernate.jpa.HibernatePersistenceProvider.createContainerEntityManagerFactory(HibernatePersistenceProvider.java:141)
hapi-fhir-jpaserver-start    | 	at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:365)
hapi-fhir-jpaserver-start    | 	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.buildNativeEntityManagerFactory(AbstractEntityManagerFactoryBean.java:409)
hapi-fhir-jpaserver-start    | 	... 107 common frames omitted
```

Full logs can be found here -> [hapi-fhir-jpaserver-start-docker.log](https://github.com/hapifhir/hapi-fhir-jpaserver-starter/files/10610822/hapi-fhir-jpaserver-start-docker.log).

# My Configuration

<details><summary>docker-compose.yml file</summary>

```yml
version: "3"
services:
  hapi-fhir-jpaserver-start:
    build: .
    container_name: hapi-fhir-jpaserver-start
    restart: on-failure
    ports:
      - "9001:8080"
  hapi-fhir-postgres:
    image: postgres:13-alpine
    container_name: hapi-fhir-postgres
    restart: always
    environment:
      POSTGRES_DB: "hapi"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    volumes:
      - hapi-fhir-postgres:/var/lib/postgresql/data
volumes:
  hapi-fhir-postgres:
```

</details>
<details><summary>src/main/resources/application.yml file</summary>

```yml
anagement:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
spring:
  main:
    allow-circular-references: true
  flyway:
    enabled: false
    check-location: false
    baselineOnMigrate: true
  datasource:
    url: 'jdbc:postgresql://hapi-fhir-postgres:5432/hapi'
    username: admin
    password: admin
    driverClassName: org.postgresql.Driver
    max-active: 15
    hikari:
      maximum-pool-size: 10
  jpa:
    properties:
      hibernate.format_sql: false
      hibernate.show_sql: false
      hibernate.dialect: ca.uhn.fhir.jpa.model.dialect.HapiFhirPostgres94Dialect
      hibernate.search.enabled: true
hapi:
  fhir:
    openapi_enabled: true
    fhir_version: R4
    advanced_lucene_indexing: false
    bulk_export_enabled: false
    bulk_import_enabled: false
    narrative_enabled: false
    mdm_enabled: false
    cors:
      allow_Credentials: true
      allowed_origin:
        - '*'
    search-coord-core-pool-size: 20
    search-coord-max-pool-size: 100
    search-coord-queue-capacity: 200
    tester:
      home:
        name: Local Tester
        server_address: 'http://localhost:8080/fhir'
        refuse_to_fetch_third_party_urls: false
        fhir_version: R4
      global:
        name: Global Tester
        server_address: "http://hapi.fhir.org/baseR4"
        refuse_to_fetch_third_party_urls: false
        fhir_version: R4
    inline_resource_storage_below_size: 4000
```

</details>

**Comment by juvarabrera** [comment]
In commit https://github.com/hapifhir/hapi-fhir-jpaserver-starter/commit/f8d749ae28dbccc173a18a28269456e87b1ea6a4#diff-b4c0421bcb3280a8e738550c830dba197057c515bcdd9579a52cbfe9adca2061, it was set to `true` and by default, it uses `elasticsearch` as `search.backend.type`

But in the following commit https://github.com/hapifhir/hapi-fhir-jpaserver-starter/commit/2e1f5f52769cf5f38883f3ac27e20f1fe1bdd84a#diff-b4c0421bcb3280a8e738550c830dba197057c515bcdd9579a52cbfe9adca2061, the `search.backend.type` was commented out which is the current version now.

✅ Setting `hibernate.search.enabled` to `false` fixed the initial issue and I was able to start FHIR successfully.
```yaml
spring:
    jpa:
        properties:
            hibernate.search.enabled: false
```

❌ Setting `hibernate.search.enabled` to `true` and using `elasticsearch` as `hibernate.search.backend.type` gave a different error.
```yaml
spring:
    jpa:
        properties:
            hibernate.search.enabled: true
            hibernate.search.backend.type: elasticsearch
            hibernate.search.backend.analysis.configurer: ca.uhn.fhir.jpa.search.HapiHSearchAnalysisConfigurers$HapiElasticAnalysisConfigurer

```

❌ Setting `hibernate.search.enabled` to `true` and using `lucene` as `hibernate.search.backend.type` and the error was the same with my initial report https://github.com/hapifhir/hapi-fhir-jpaserver-starter/issues/493#issue-1571393664 which I would assume when set to `true`, by default it would use `lucene`
```yaml
spring:
    jpa:
        properties:
            hibernate.search.enabled: true
            hibernate.search.backend.type: lucene
            hibernate.search.backend.analysis.configurer: ca.uhn.fhir.jpa.search.HapiHSearchAnalysisConfigurers$HapiLuceneAnalysisConfigurer
            hibernate.search.backend.directory.type: local-filesystem
            hibernate.search.backend.directory.root: target/lucenefiles
            hibernate.search.backend.lucene_version: lucene_current
```

I may be missing something why the last 2 had errors but, for now, to fix this reported issue, I just had to set `hibernate.search.enabled` to `false` for now.
