### ISSUE TITLE
Configure HTTPS in application.yaml

### ISSUE THREAD

**Issue by iagarcia** [hapifhir/hapi-fhir-jpaserver-starter#510]
Hello, I'm trying to use HTTPS but the configuration file application.yaml it seems that it not recognize directive.
I've set this
```
    ### enable to use the ApacheProxyAddressStrategy which uses X-Forwarded-* headers
    ### to determine the FHIR server address
    use_apache_address_strategy: true
    ### forces the use of the https:// protocol for the returned server address.
    ### alternatively, it may be set using the X-Forwarded-Proto header.
    use_apache_address_strategy_https: true
```
Other problem is that I can't change FHIR Base http://localhost:8080/fhir
in this section

```
tester:
      home:
        name: Local Tester
        server_address: "https://<MY_DOMAIN>/fhir"
        refuse_to_fetch_third_party_urls: false
        fhir_version: R4
```

The main error it shown on website
```
Fetch error
NetworkError when attempting to fetch resource. http://<MY_DOMAIN>/fhir/api-docs?page=System Level Operations
Fetch error
Possible mixed-content issue? The page was loaded over https:// but a http:// URL was specified. Check that you are not attempting to load mixed content
```

What am I missing? Regards
Ignacio

**Comment by XcrigX** [comment]
I'm not certain about your entire question, but I am using HTTPS by setting the Spring servlet properties like:

```
server: 
  port: 8443
  ssl:
    enabled: true
    protocol: TLS
    enabled-protocols: 'TLSv1.2,TLSv1.3'
    key-store-type: PKCS12
    key-store: '/pathto/mycertificate.p12'
    #key-store-password: 
```

I'm not explicitly setting _use_apache_address_strategy_, but use _server_address_ to specify the public base URL.
