### ISSUE TITLE
Unable to locate Interceptor class using docker

### ISSUE THREAD

**Issue by fhnaumann** [hapifhir/hapi-fhir-jpaserver-starter#534]
I have a super basic docker-hapi-fhir setup and I cannot get it to work properly.
`docker-compose.yml`:
```yml
version: '3.7'

services:
  fhir:
    container_name: fhir
    image: "hapiproject/hapi:latest"
    ports:
      - "8080:8080"
    configs:
      - source: hapi
        target: /app/config/application.yaml
      - source: hapi-extra-classes
        target: /app/extra-classes
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: hapi
    volumes:
      - psql:/var/lib/postgresql/data
volumes:
  psql:
configs:
  hapi:
    file: ./hapi.application.yaml
  hapi-extra-classes:
    file: ./hapi-extra-classes
```
`hapi-application.yaml`:
```yaml
spring:
  datasource:
    url: 'jdbc:postgresql://db:5432/hapi'
    username: admin
    password: admin
    driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate.dialect: ca.uhn.fhir.jpa.model.dialect.HapiFhirPostgres94Dialect
      hibernate.search.enabled: false
hapi:
  fhir:
    custom-bean-packages: the.containing.your.interceptor
    custom-interceptor-classes: the.containing.your.interceptor.YourInterceptor
```
`YourInterceptor`:
```java
package the.containing.your.interceptor;

import org.hl7.fhir.instance.model.api.IBaseResource;

import ca.uhn.fhir.interceptor.api.Hook;
import ca.uhn.fhir.interceptor.api.Interceptor;
import ca.uhn.fhir.interceptor.api.Pointcut;

@Interceptor
public class YourInterceptor
{
    @Hook(Pointcut.STORAGE_PRECOMMIT_RESOURCE_CREATED)
    public void resourceCreated(IBaseResource newResource)
    {
        System.out.println("YourInterceptor.resourceCreated");
    }
}
```
When I run `docker compose up` I get the following exception:
```
Caused by: ca.uhn.fhir.context.ConfigurationException: Interceptor class was not found on classpath: the.containing.your.interceptor.YourInterceptor
at ca.uhn.fhir.jpa.starter.common.StarterJpaConfig.registerCustomInterceptors(StarterJpaConfig.java:438)
```
If I manually look at the files present inside the docker container with `docker cp <container id>:/app temp` the file structure `extra-classes/the/containing/your/interceptor/YourInterceptor.java` clearly exists and is correctly copied into the container.

When I replace the custom interceptor with any class from the standard java library, e.g. `java.lang.Thread` in the `hapi.application.yaml` then the (useless) interceptor is found.
