### ISSUE TITLE
interception order

### ISSUE THREAD

**Issue by dieterbusch** [hapifhir/hapi-fhir-jpaserver-starter#538]
Dear HAPI Team, 

there is a problem in the interception order. Since a few days I am debugging the problem that the React app "SMART-Patient-Browser" expects the header "Access-Control-Allow-Origin" and the related "Access-Control-Allow-Headers". I was able to solve the problem by registering my interceptor at the level of line 312 (StarterJpaConfig). However, when I use the custom-interceptor-classes mechanic, the interceptor is registered way too late and not used. So my suggestion for improvement:
1. to place the call registerCustomInterceptors higher up 
2. or even better add allowed_headers to AppProperties
3. or add this lines to the default Cors Interceptor: 
```
     config.addAllowedHeader(HttpHeaders.ACCESS_CONTROL_ALLOW_ORIGIN);
     config.addAllowedHeader(HttpHeaders.ACCESS_CONTROL_ALLOW_HEADERS);
     config.addAllowedHeader(HttpHeaders.ACCESS_CONTROL_ALLOW_METHODS);
```
Another suggestion for a better understanding of the README.md: in the folder HAPI-extra-classes the custom-interceptor must be a .class file. To create it, the import paths must be valid and present. In order for the server to find the extra-classes via docker-compose, I had to generate the corresponding extra-class under the hapi project via mvn install and copy it out of the target directory. The hint in the readme might help.

Thanks for the hard work.

**Comment by XcrigX** [comment]
One other option you have which I think would work is to define your own custom CorsInterceptor.  You'd have to turn 'allow-bean-definition-overriding' on in the config, use 'custom-bean-packages' to discover your interceptor, and use a "@Primary" annotation on it so yours would be picked up over the default.  I don't think you'd want to reference it with with 'custom-interceptor-classes' as that may cause it to try to be registered twice.

**Comment by dieterbusch** [comment]
Good idea. But it does not work. What am I doing wrong?

hapi-extra-classes/a/b/c/CustomCors.class: 
```
package a.b.c;
@Component
public class CustomCors {
	@Bean
	@Primary
	public CorsInterceptor corsInterceptor() {
           ...
	}
}
```
hapi.application.yaml:
```
spring:
  main:
    allow-bean-definition-overriding: true
hapi:
  fhir:
    custom-bean-packages: a.b.c
```
docker-compose.yaml:
```
ds-fhir-server:
    image: "hapiproject/hapi:latest"
    ports:
      - 8888:8888
    volumes:
      - fhir-server-data:/data/hapi
    configs:
      - source: hapi-application-config
        target: /app/config/application.yaml
      - source: hapi-extra-classes
        target: /app/extra-classes
configs:
  hapi-application-config:
    file: ./hapi.application.yaml
  hapi-extra-classes:
    file: ./hapi-extra-classes
```
