### ISSUE TITLE
Unable to include implementation guide in helm chart

### ISSUE THREAD

**Issue by gmej** [hapifhir/hapi-fhir-jpaserver-starter#549]
Reading the Helm chart documentation, there is no possibility to include an implementation guides in the values.yaml file. The only current option to do it is editing the application.yaml file and building the image locally, but it would be better to include this an implementation guides directly in the values.yaml so that the official docker.io image can be used with implementation guides.

**Comment by chgl** [comment]
You can override all settings in the application.yaml as environment variables. You can set them using the `extraEnv` value.

As an alternative, one could add a way to mount custom volumes, e.g. from configmaps to override the application.yaml with a custom one - or one to merge with the default values. PRs welcome!

**Comment by gmej** [comment]
I ma trying to use `extraEnv`and can't get to a solution. I want to translate this example in `application..yaml`:
```yaml
hapi:
  fhir:
    implementationguides:
      gh_0_1_0:
        url: https://build.fhir.org/ig/hl7-eu/gravitate-health/package.tgz
        name: hl7.eu.fhir.gh
        version: 0.1.0
```

to `extraEnv`. I am trying this, but it doesn't work:
```yaml
extraEnv:
  - name: HAPI_FHIR_IMPLEMENTATIONGUIDES_GH-0.1.0_URL
    value: https://build.fhir.org/ig/hl7-eu/gravitate-health/package.tgz
  - name: HAPI_FHIR_IMPLEMENTATIONGUIDES_GH-0.1.0_NAME
    value: hl7.eu.fhir.gh
  - name: HAPI_FHIR_IMPLEMENTATIONGUIDES_GH-0.1.0_VERSION
    value: 0.1.0
```

How should I write an extraEnv when the value of a key is a list of objects?
