### ISSUE TITLE
Bug in R5 with HAPI FHIR v6.6.0

### ISSUE THREAD

**Issue by gmej** [hapifhir/hapi-fhir-jpaserver-starter#550]
I have my FHIR server (R5) in version v6.5-tracking, deployed with Helm chart. When trying to upgrade to v6.6.0, I got an error reporting a missing bean "ca.uhn.fhir.jpa.subscription.match.deliver.email.IEmailSender".

The workaround was to include this on my application.yaml: 
```
hapi:
  fhir:
    subscription:
      email:
        from: some@test.com
        host: google.com
```

This subscription information is not an actual email, I typed the first values I thought about and it worked, I feel that any `from`  and `host` values would make the server work again.

The expected behaviour would be that the server works WITHOUT having to add this subscription information.
