### ISSUE TITLE
FHIR R5 with SQL Server 2019 Error creating bean with name 'subscriptionTopicMatchingSubscriber'

### ISSUE THREAD

**Issue by binoynair** [hapifhir/hapi-fhir-jpaserver-starter#578]
Hi,  I am trying to run Hapi FHIR v6.8.0 with FHIR R5 version and MS SQL Server 2019. 

It fails to create the container with the Exception encountered during context initialization. Error creating bean with name 'subscriptionTopicMatchingSubscriber'

docker run --name hapi_fhir_server_v6.8.0_r5 -p 8080:8080 -v "$(pwd)/configs:/configs" -e "--spring.config.location=file:///configs/another.r5.application.yaml" hapi-fhir/hapi-fhir-jpaserver-starter:latest

Log file:[
[log hapi fhir v6.8.0.txt](https://github.com/hapifhir/hapi-fhir-jpaserver-starter/files/12403621/log.hapi.fhir.v6.8.0.txt)
](url)

another.r5.application.yml file: [
[another.r5.application.zip](https://github.com/hapifhir/hapi-fhir-jpaserver-starter/files/12403637/another.r5.application.zip)
](url)

Note: SQL Server 2019 has default collation of case insensitive

appreciate your help!

Thanks,
B

**Comment by hlab-pawat** [comment]
Hi, I also experience the same problem but with Postgres. I make it works by uncomment subscription line in application.yaml like below

```
hapi:
  fhir:
    openapi_enabled: true
    fhir_version: R5
    cors:
      allow_Credentials: true
      allowed_origin:
        - '*'
    subscription:
      resthook_enabled: true
      # websocket_enabled: false
      email:
        from: some@test.com
        host: google.com
        port:
        username:
        password:
        auth:
        startTlsEnable:
        startTlsRequired:
        quitWait:
```

The email doesn't have to be correct for start the server. However to use subscription feature, the email must be correct.
