### ISSUE TITLE
Unable to add US Core IG

### ISSUE THREAD

**Issue by endue-phihoang** [hapifhir/hapi-fhir-jpaserver-starter#603]
* FHIR Version: R4
* US-Core Version: 6.1.0

Hi forks, I'm trying to install a FHIR on local using docker-compose using these settings:
`docker-compose.yml`:
```
version: '3.7'

services:
  fhir:
    container_name: fhir
    image: "hapiproject/hapi:latest"
    ports:
      - "8080:8080"
    configs:
      - source: hapi
        target: /app/config/application.yaml
    depends_on:
      - db


  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: hapi
    ports:
      - "55432:5432"
    volumes:
      - ./hapi.postgress.data:/var/lib/postgresql/data

configs:
  hapi:
    file: ./hapi.application.yaml
``` 
`hapi.application.yaml`:
```
spring:
  datasource:
    url: 'jdbc:postgresql://db:5432/hapi'
    username: admin
    password: admin
    driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate.dialect: ca.uhn.fhir.jpa.model.dialect.HapiFhirPostgres94Dialect
      hibernate.search.enabled: false
hapi:
  fhir:

    ### This enables the swagger-ui at /fhir/swagger-ui/index.html as well as the /fhir/api-docs (see https://hapifhir.io/hapi-fhir/docs/server_plain/openapi.html)
    openapi_enabled: true
    fhir_version: R4
    implementationguides:
      us-core:
        packageUrl: https://hl7.org/fhir/us/core/STU6.1/package.tgz
        name: hl7.fhir.us.core
        version: 6.1.0
        installMode: STORE_AND_INSTALL
```
Startup command:
`docker-compose up`
Here is the startup log
[startup_log.txt](https://github.com/hapifhir/hapi-fhir-jpaserver-starter/files/13213951/startup_log.txt)
I met some errors like:
```
fhir                              | 2023-10-31 08:29:49.226 [hapi-fhir-jpa-scheduler-clustered-4] ERROR ca.uhn.fhir.jpa.term.TermReadSvcImpl [TermReadSvcImpl.java:2396] Failed to pre-expand ValueSet: HAPI-0889: Unknown ValueSet: http%3A%2F%2Fcts.nlm.nih.gov%2Ffhir%2FValueSet%2F2.16.840.1.113762.1.4.1099.24
fhir                              | ca.uhn.fhir.rest.server.exceptions.ResourceNotFoundException: HAPI-0889: Unknown ValueSet: http%3A%2F%2Fcts.nlm.nih.gov%2Ffhir%2FValueSet%2F2.16.840.1.113762.1.4.1099.24
```
or 
```
fhir                              | 2023-10-31 08:29:49.333 [hapi-fhir-jpa-scheduler-clustered-4] ERROR ca.uhn.fhir.jpa.term.TermReadSvcImpl [TermReadSvcImpl.java:2396] Failed to pre-expand ValueSet: HAPI-0888: org.hl7.fhir.common.hapi.validation.support.InMemoryTerminologyServerValidationSupport$ExpansionCouldNotBeCompletedInternallyException: HAPI-0702: Unable to expand ValueSet because CodeSystem could not be found: http://www.ama-assn.org/go/cpt
fhir                              | ca.uhn.fhir.rest.server.exceptions.InternalErrorException: HAPI-0888: org.hl7.fhir.common.hapi.validation.support.InMemoryTerminologyServerValidationSupport$ExpansionCouldNotBeCompletedInternallyException: HAPI-0702: Unable to expand ValueSet because CodeSystem could not be found: http://www.ama-assn.org/go/cpt
```
Can some one help me take a look on it?
