### ISSUE TITLE
Unable to Perform Health Checks with Hapi FHIR in Docker Swarm

### ISSUE THREAD

**Issue by brett-onions** [hapifhir/hapi-fhir-jpaserver-starter#646]
Issue Description:
We are currently using Hapi Fhir (specifically the Hapi Fhir Starter) within Docker Swarm to manage our services. Our objective is to conduct health checks to monitor the current state of the service. Hapi FHIR provides a designated endpoint for health checks at /actuator/health, which we intend to utilize for this purpose.

However, we encountered a challenge while attempting to implement this. Our preference was to utilize the official image hapiproject/hapi. Regrettably, we encountered difficulty performing curl or wget commands to access the health check endpoint due to the absence of these applications within the image.

``` yml
//docker-compose.yaml

healthcheck:
      test: /bin/curl --no-verbose --tries=1 --spider http://localhost:8080/actuator/health
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 2m
````
I seeking guidance on how to effectively conduct the health check without resorting to the creation of a separate image solely for the installation of curl or wget.
