### ISSUE TITLE
Docker image tags mismatch with HAPI FHIR version

### ISSUE THREAD

**Issue by gmej** [hapifhir/hapi-fhir-jpaserver-starter#664]
I have deployed with Helm, with the following config in `values.yaml`

```yaml
image:
  registry: docker.io
  repository: hapiproject/hapi
  tag: "v7.0.2"
  pullPolicy: Always
```

But the /metadata endpoint reports being v7.0.0

```json
{
    ...
    "software": {
        "name": "HAPI FHIR Server",
        "version": "7.0.0"
    }
    ...
}
```

Is this a problem on my side? Or maybe Docker images aren't correctly tagged? Building source (in version v7.0.2) in a new Docker Image does report the correct version "v7.0.2" in the /metadata endpoint
