### ISSUE TITLE
Issue with prometheus configuration v7.4.0

### ISSUE THREAD

**Issue by joofio** [hapifhir/hapi-fhir-jpaserver-starter#741]
Hi, I am trying to (re)add the prometheus export in v7.4.0 with:
```
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
```
and not getting prometheus. I am doing something wrong? 
Current server with this config at: https://sandbox.hl7europe.eu/baseserver/actuator
