### ISSUE TITLE
How to contribute to add to docs

### ISSUE THREAD

**Issue by omargalal20** [hapifhir/hapi-fhir-jpaserver-starter#805]
I was trying to run the starter project locally using Docker Compose with Postgres, but it not containerized. I found the following configuration worked with me, I am using Windows. So wanted to see how to contribute to the project and updating the README if its a viable solutions.

References:
https://docs.docker.com/desktop/features/networking/#use-cases-and-workarounds
https://www.howtogeek.com/devops/how-to-connect-to-localhost-within-a-docker-container/

### PostgreSQL configuration

To configure the starter app to use PostgreSQL on your local host that is not containerized, update the application instead of the default H2.yaml file to have the following:

To connect from a container to a service on the host

- For Windows and Mac:

```docker
name: hapi-fhir-server

services:
  fhir:
    container_name: fhir
    image: "hapiproject/hapi:latest"
    ports:
      - "8080:8080"
    configs:
      - source: hapi
        target: /app/config/application.yaml

configs:
  hapi:
    file: ./hapi.application.yaml
```

```yaml
spring:
  datasource:
    url: 'jdbc:postgresql://host.docker.internal:5432/hapi'
    username: admin
    password: admin
    driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate.dialect: ca.uhn.fhir.jpa.model.dialect.HapiFhirPostgresDialect
      hibernate.search.enabled: false

      # Then comment all hibernate.search.backend.*
```

- For Linux:

```docker
name: hapi-fhir-server

services:
  fhir:
    container_name: fhir
    image: "hapiproject/hapi:latest"
    ports:
      - "8080:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    configs:
      - source: hapi
        target: /app/config/application.yaml

configs:
  hapi:
    file: ./hapi.application.yaml
```

```yaml
spring:
  datasource:
    url: 'jdbc:postgresql://host.docker.internal:5432/hapi'
    username: admin
    password: admin
    driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate.dialect: ca.uhn.fhir.jpa.model.dialect.HapiFhirPostgresDialect
      hibernate.search.enabled: false

      # Then comment all hibernate.search.backend.*
```
