### ISSUE TITLE
Enable full text search in docker container

### ISSUE THREAD

**Issue by Yes25** [hapifhir/hapi-fhir-jpaserver-starter#807]
I tried to enable full text search with the prebuilt docker image and Lucene but can't get it to work. 

I tried this compose file:
```yaml
services:
  fhir:
    container_name: fhir
    image: "hapiproject/hapi:latest"
    ports:
      - "8080:8080"
    configs:
      - source: hapi
        target: /app/config/application.yaml

configs:
  hapi:
     file: ./hapi.application.yaml
```

along with this application.yaml:
```yaml
spring:
  datasource:
    url: 'jdbc:h2:file:./target/database/h2'
    #url: jdbc:h2:mem:test_mem
    username: sa
    password: null
    driverClassName: org.h2.Driver
    max-active: 15

    # database connection pool size
    hikari:
      maximum-pool-size: 10
  jpa:
    properties:
      hibernate.dialect: ca.uhn.fhir.jpa.model.dialect.HapiFhirH2Dialect
      hibernate.search.enabled: true
      # lucene parameters
      hibernate.search.backend.type: lucene
      hibernate.search.backend.analysis.configurer: ca.uhn.fhir.jpa.search.HapiHSearchAnalysisConfigurers$HapiLuceneAnalysisConfigurer
      hibernate.search.backend.directory.type: local-filesystem
      hibernate.search.backend.directory.root: target/lucenefiles
      hibernate.search.backend.lucene_version: lucene_current

hapi.fhir.store_resource_in_lucene_index_enabled: true
```

If I send a request like:
```
http://localhost:8080/fhir/Patient?_content:contains=xyz
```
I get back a `400 Bad Request` with the message:
```json
{
    "resourceType": "OperationOutcome",
    "issue": [
        {
            "severity": "error",
            "code": "processing",
            "diagnostics": "HAPI-2566: Fulltext searching is not enabled on this server, can not support the parameter(s): _content"
        }
    ]
}
```

Am I missing something?

**Comment by henryosei** [comment]
You can look at how the application.yml is structured. Try using this snippet below:

hapi.fhir.jpa:
  search:
    allow_multiple_search_results: true
  fulltext_search_enabled: true

Also full-text search support is available in HAPI FHIR v5.0 and above. If you're using an older version, you may need to upgrade to a newer version that supports this feature.

**Comment by Yes25** [comment]
Thank you for the reply @henryosei. 

I tried the suggested snippet but still no luck. I was looking at this [application.yml](https://github.com/hapifhir/hapi-fhir-jpaserver-starter/blob/master/src/main/resources/application.yaml). Ist that the correct one? Shouldn't I be able to find the attributes you suggested (`allow_multiple_search_results` , `fulltext_search_enabled`) in there somewhere?

**Comment by iamsauravsharma** [comment]
Anyone got idea what was changed looks like version `7.6.0` was working with same `application.yaml` but new version `8.0.0` is not working

common application.yaml for both version
```yaml
spring:
  jpa:
    properties:
      hibernate.search.enabled: true
      hibernate.search.backend.type: lucene
      hibernate.search.backend.analysis.configurer: ca.uhn.fhir.jpa.search.HapiHSearchAnalysisConfigurers$HapiLuceneAnalysisConfigurer
      hibernate.search.backend.directory.type: local-filesystem
      hibernate.search.backend.directory.root: target/lucenefiles
      hibernate.search.backend.lucene_version: lucene_current
```
docker-compose.yaml file
```yaml
version: '3.7'

services:
  fhir-7.6:
    container_name: fhir-7.6.0
    restart: always
    image: hapiproject/hapi:v7.6.0
    ports:
      - "8080:8080"
    configs:
      - source: hapi
        target: /app/config/application.yaml
  fhir-8:
    container_name: fhir-8.0.0
    restart: always
    image: hapiproject/hapi:v8.0.0
    ports:
      - "8088:8080"
    configs:
      - source: hapi
        target: /app/config/application.yaml

configs:
  hapi:
     file: ./hapi.application.yaml
```
Request to version 7.6.0
```bash
curl localhost:8080/fhir/Observation?_content:contains=Glucose
{
  "resourceType": "Bundle",
  "id": "70c29bb6-9f3e-4611-90fc-30d50d9d8366",
  "meta": {
    "lastUpdated": "2025-05-26T07:34:12.470+00:00"
  },
  "type": "searchset",
  "total": 0,
  "link": [ {
    "relation": "self",
    "url": "http://localhost:8080/fhir/Observation?_content%3Acontains=Glucose"
  } ]
```
Same request to version 8.0.0
```bash
curl localhost:8088/fhir/Observation?_content:contains=Glucose
{
  "resourceType": "OperationOutcome",
  "issue": [ {
    "severity": "error",
    "code": "processing",
    "diagnostics": "HAPI-2566: Fulltext searching is not enabled on this server, can not support the parameter(s): _content"
  } ]
```
