### ISSUE TITLE
ClassCastException during snomed CodeSystem $lookup with RemoteTerminology server as Snowstorm Terminology Server

### ISSUE THREAD

**Issue by centaurusgod** [hapifhir/hapi-fhir-jpaserver-starter#834]
Issue probably linked to: [#5699](https://github.com/hapifhir/hapi-fhir/issues/5699)

Performing CodeSystem $lookup on remote terminology server set as https://tx.fhir.org/r4/ is fine but using snowstorm as terminology server results in this error.
```
curl --request GET \
  --url 'http://localhost:8080/fhir/CodeSystem/$lookup?system=http%3A%2F%2Fsnomed.info%2Fsct&code=134006&_format=json' \
  --header 'Content-Type: application/fhir+json'
```
![Image](https://github.com/user-attachments/assets/716437f7-3361-4e17-88ce-1872f8d91c4a)

**Comment by jkiddo** [comment]
What does your configuration look like?

**Comment by centaurusgod** [comment]
@jkiddo 
Thanks for replying.
The configuration was:
```
    remote_terminology_service:
     snomed:
       system: 'http://snomed.info/sct'
       url: 'https://fhir.our_domain.org/r4/'
```
https://fhir.our_domain.org/r4/ this is the base url where we have hosted our snowstorm terminology server.
